### ISSUE TITLE
401 unauthorized when trying to download epub

### ISSUE THREAD

**Issue by l3d00m** [patrickvogel/zeit-on-tolino#3]
It seems like ZEIT changed their authorization format somehow (?) because you no longer can download the ePubs. 

If fails with `an error occurred: Request failed (401)`. The error occurs in [this line](https://github.com/patrickvogel/zeit-on-tolino/blob/8ad796c4c56f918f90c9d69229cde3216c042b89/src/zeitOnTolino.py#L63).

I'm not sure how they do their authorization now, but I assume it's now cookie based instead of Basic authorization?

Thanks for the tool anyways, it was very helpful for me over the last months! If you shouldn't have the time to look into this, then I'll try to find a solution.

**Comment by patrickvogel** [comment]
Yep, they changed the location & authorization method for epub-file downloads ... should be fixed now :-)

Thanks for your feedback! I already wondered why the latest edition didn't appear on my Tolino, but didn't check the logs yet.

**Comment by l3d00m** [comment]
Great, thanks for the quick fix!
